### ISSUE TITLE
about the embedding the positions of entities  

### ISSUE THREAD

**Issue by samithaj** [thunlp/OpenNRE#10]
i'm trying to understand how this **output** matrix is created to embed the positions of related entities

could you please tell me why these specific type of embedding(where did 60,122 numbers came form in pos_embed() ) is used and how are these type of embedding helps to create a better model

in initial.py
line 5:
```
`def pos_embed(x):
	if x < -60:
		return 0
	if x >= -60 and x <= 60:
		return x+61
	if x > 60:
		return 122
`
```
line 124:
````
for i in range(fixlen):  #1-70
			word = word2id['BLANK']
			rel_e1 = pos_embed(i - en1pos)
			rel_e2 = pos_embed(i - en2pos)
			output.append([word,rel_e1,rel_e2])
		for i in range(min(fixlen,len(sentence))):
			word = 0
			if sentence[i] not in word2id:
				word = word2id['UNK']
			else:
				word = word2id[sentence[i]]			
			output[i][0] = word
````

**Comment by Tsingularity** [comment]
1. The position embedding.

The position embedding is a vector concatenated with the word embedding. It represent the relative distance between the current word and the entity word.

2. What does 70 mean?

Due to the fact that most sentences in the dataset are less than 70 words, I set the fixed length of sentence to be 70 words.(for the sentences contain less than 70 words, I pad them with "BLANK" word, for the sentences more than 70 words, I ignore the 70+ part). 

3. What does 60 and 122 mean?

Due to the fixed length of sentence, I set the range of relative distance to be (-60,60). Each distance in the range has its own embedding vector. For the distance out of the range(>60 or <-60), they have only two embedding vector because they don't appear a lot. (>60 has one and <-60 has one) So it has 122 in total.

**Comment by samithaj** [comment]
Thanks for replying and thanks for sharing the project!!

**Comment by Musawar71** [comment]
hello. I also need help in this can some one help

**Comment by ShellingFord221** [comment]
Hi, I have another question about position embedding. In NYT dataset, there are some sentences that e1 or e2 appears more than 1 time. For example, these sentences may like _ _ _ e1 _ _ e2 _ _ _ e2 _ _. The relative distance of e1 is out of question, but the relative distance of e2 is ambiguous. How do you embed positions in this situation? Thanks!
