### ISSUE TITLE
model selection

### ISSUE THREAD

**Issue by lephong** [thunlp/OpenNRE#125]
It seems that the source code stores only the best model evaluated on the test data when training (the model with the best metric - i.e. AUC). If that's true, is it weird? (Because we are not allowed to use the test data for tuning (here early stopping).)

**Comment by gaotianyu1350** [comment]
It is mainly due to that NYT10 dataset only has `train` and `test` sets, without a validation set, so we treat the `test` set also as the validation set, which might cause the problem you mentioned. Later we will release a distant dataset with `train`, `val` and `test` subsets and experiments will be carried out as the standard way.
