### ISSUE TITLE
evalution promblem

### ISSUE THREAD

**Issue by KODGV** [thunlp/OpenNRE#126]
the test evalution codes are here:
```      
for i, item in enumerate(sorted_test_result[::-1]):
            correct += item['flag']
            prec.append(float(correct) / (i + 1))
            recall.append(float(correct) / self.test_data_loader.relfact_tot)
auc = sklearn.metrics.auc(x=recall, y=prec)
```
i think 'correct' records the times of  right answers
But  when my y_pre is the same as y_true,auc is still not equal to 1.
So is it something wrong about the recall?why should it divide relation_nums every time

**Comment by gaotianyu1350** [comment]
> Why should it (recall) divide relation_nums every time

It's `num of relation facts (triples)` instead of `num of relations`.

> auc is still not equal to 1

Are you sure all the predicted results are true? If so, is the value of `auc` close to `1`? If there are some negative samples, there will be some points on `recall=1` line with different `precision` values, which might cause the `auc` function to give result rather than `1`.
