### ISSUE TITLE
Question about relation for each sentence in training/test data.

### ISSUE THREAD

**Issue by frankxu2004** [thunlp/OpenNRE#15]
I have some difficulty figuring out where exactly the relation in each line of train.txt and test.txt

Since each entity pair could have multiple possibilities of relations, how do you label the sentences with the relation of the two entities? From my understanding, the distant supervision would require no exact sentence-level labeled relation. So how are the train.txt and test.txt produced?

Thanks

**Comment by Tsingularity** [comment]
Your understanding about distant supervision is basically right. It's true that distant supervision requires no exact sentence-level labeled relation. 
As for the train/test.txt's production, for example, if there's a triple (head_entity a,relation r, tail_entity b) exists in Freebase, we just label all the sentences (in out corpus) which contain the entity a and b with the relation r. Due to the fact that the same entity pair may contains multiple relations in knowledge graph, one sentence may also contains multiple relation labels. But this may also cause the problem of noisy or even incorrect label. Here are some examples:
For instance, the sentences "Beijing is the city of China" and "Beijing is the capital of China" are both labeled the relation "city_of" and "capital_of" in the distant supervision. But it is obvious that the first sentence describes the first relation and the second sentence describes the second.
For another example, the sentences "Bill Gates loves Microsoft" and "Bill Gates is the founder of Microsoft" are both labeled as relation "founder_of" in distant supervision, but it is obvious that the first sentence doesn't describe any information of the relation.
And that's why we need sentence-level attention to address this problem.

**Comment by frankxu2004** [comment]
Thanks a lot for the clarification. Now the training and test data are clearer to me.
So basically, If for one entity pair (a, b), there are k possible relations r concerning (a, r, b) existing in Freebase, and have a set of n sentences that contains both a and b, there will be k*n items in the data file for each of this specific pair (a, b). Am I understanding right?

**Comment by Tsingularity** [comment]
Yes， I think you are right.

**Comment by snowxiaoru** [comment]
你好，我这里有两个疑问
(1)训练的时候对每对关系找到 n个句子组成一个bag，那预测的时候对 (entity_a,entity_b)是否也需要找到n个句子组成一个bag进行预测，只有bag有一个是预测正确的，则说明成立？
(2)那如果不足n个,怎么办呢？

**Comment by THUCSTHanxu13** [comment]
n是不固定的
