### ISSUE TITLE
guid to mid conversion

### ISSUE THREAD

**Issue by fenchri** [thunlp/OpenNRE#287]
Hi there,

I would like to ask if it is safe to convert GUIDs to MIDs? 
If so, could you provide a conversion, since the provided dataset uses guids?

Thanks in advance!

**Comment by gaotianyu1350** [comment]
Why would you like to convert guids to mids? Also, I am not sure which MID you are referring to.

**Comment by fenchri** [comment]
Hi, sorry I should have been more specific. I am referring to the NYT10 dataset, that originally (in previous versions 570K and 522L) came with mids (e.g. m.03frx9g) rathen than guids.
I would like this for alignment with subsets of Freebase that contain mids.

**Comment by gaotianyu1350** [comment]
I see... Sorry that I don't really remember the details since the data are converted very long before. There is [a version of the data](https://github.com/thunlp/NRE/blob/master/data.zip) that use the MID you mentioned. Maybe you can use this version of data. I will take some time to look into it (maybe guid and mid are two keys in the original data).

**Comment by fenchri** [comment]
No problem, I found a conversion here: https://github.com/knightBoy/riedel_dataset/blob/master/src/python/pb_to_tsv.py#L23
Maybe this is fine?

**Comment by gaotianyu1350** [comment]
Oh I think that is what you are looking for. Great!
