### ISSUE TITLE
problem in different bert version

### ISSUE THREAD

**Issue by mouxiaofeng1981** [thunlp/OpenNRE#316]
在最新的transformers/bert 4.2版本上，bert的输出格式改变了，对opennre 主要影响是：opennre/encoder/bert_encoder.py，该文件修改两处：

//行是现有代码，非//行我修改后的结果，可以实验通过。

第32行：
// _, x = self.bert(token, attention_mask=att_mask)
// return x        
ret = self.bert(token, attention_mask=att_mask)
return ret.last_hidden_state

第135行：
// hidden, _ = self.bert(token, attention_mask=att_mask)
ret = self.bert(token, attention_mask=att_mask)
hidden = ret.last_hidden_state

**Comment by QiaoZiqing** [comment]
As Olivier Terrier said, the output of BertModel in the latest version of transformers has two forms, one is BaseModelOutputWithPoolingAndCrossAttentions, and the other is a tuple of torch. In the new version, by default, the BaseModelOutputWithPoolingAndCrossAttentions class unifies the output of the Models. If we still want to use the previous code, we need to pass an additional parameter (return_dict=False) so that the return value of BertModel is still a tuple of torch.

> _, x = self.bert(token, attention_mask=att_mask, return_dict=False)

Modifications have been made to address this issue.
