### ISSUE TITLE
Not finding file

### ISSUE THREAD

**Issue by LiNengRan** [thunlp/OpenNRE#324]
After installing everything and running all the download .sh (pretrain and bench mark), still when running the 3-line sample program the line below does NOT get this model. Where is it?

model = opennre.get_model('wiki80_bert_softmax')

Fails with:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/nameofuser/opennre/pretrain/nre/wiki80_bert_softmax.pth.tar'

**Comment by LiNengRan** [comment]
How is the .../pretrain/nre directory created? This is not done by setup or by the pretrain or benchmark .sh scripts.

**Comment by joelawalsh01** [comment]
I'm having the same problem.

**Comment by joelawalsh01** [comment]
do a wget command and paste in the directory of the file:

wget -P ner https://thunlp.oss-cn-qingdao.aliyuncs.com/opennre/pretrain/nre/wiki80_bertentity_softmax.pth.tar

**Comment by joelawalsh01** [comment]
sorry should say nre not ner

**Comment by gaotianyu1350** [comment]
Hi,

When you run `get_model`, the folders and the data files should be created and downloaded automatically. I'm not sure why in your case the package failed to do so (probably due to the system difference, it seems that you are using Mac). If this happens, you can just download the model manually and put it in the folder.
