### ISSUE TITLE
What is the true usage of settings.big_num?

### ISSUE THREAD

**Issue by frankxu2004** [thunlp/OpenNRE#6]
Shall i understand the settings.big_num in the training part as the batchsize that controls how many samples are feed until an optimization is executed?
and why in test_GRU.py, it is set by test_settings.big_num = 262 * 9.
I'm a little confused about why it is 262*9

Thank you

**Comment by Tsingularity** [comment]
Yes, the settings.big_num refers to the number of entity pairs which are fed into the network while training/testing.
However during testing, the total number of the entity pairs you want to test should be divided by the big_num with no remainder. And that's why it is set as 262*9. You can also factor the number of the entity pairs you want test and set the big_num according to the results.
But you should note that when the big_num is small, the time of forward process will be a little bit long. However if the big_num is too big, the memory may be out of usage. So, you should try and find a balance.

**Comment by frankxu2004** [comment]
Thanks a lot. It was really quick response. Now it's a lot clearer!
