### ISSUE TITLE
any readme about the dataset format

### ISSUE THREAD

**Issue by loveJasmine** [thunlp/OpenNRE#65]

**Comment by gaotianyu1350** [comment]
You should contain these files in origin_data for further processing:

train.txt：corpus for training
test.txt：corpus for testing
vec.txt：word vector file
relation2id.txt: mapping relations to their corresponding ids.

## Train and Test Files

Train and test.txt have the same format. Each line of them is an instance containing an entity pair and a sentence, in the format of,

`head_entity_id tail_entity_id head_entity tail_entity relation sentence ###end###`

For example,

`m.03_3d	m.07dfk	japan	tokyo	/location/country/capital	the meeting came as japan has troops on a humanitarian mission in iraq , the first time tokyo has deployed its forces into a combat zone since world war ii . ###END###`

Make sure every unique word has a unique entity id. PAY ATTENTION: there are spaces between punctuations and words.

## Word Vector File
There are two numbers, n and m, in the first line, meaning the number of words and the dimension of word vector respectively.

For the next n lines, there are a word (numbers and punctuations also belong to 'words') and m numbers separated by spaces in each line, representing the word and its vector.

## Relation-id Mapping File

First line contains a single number n, meaning the total number of relations.

Each of the next n lines contains a relation name and its corresponding id, which is from 0 to n - 1.

**Comment by LambdaWs** [comment]
There are not have the total number of relations at first line   in Relation-id Mapping File

**Comment by LambdaWs** [comment]
There are not have the total number of relations at first line   in Relation-id Mapping File

**Comment by danem** [comment]
Is this guidance still more or less accurate for the new JSON version? Specifically, I'm unclear what the "other information" refers to in the training and test data specification laid out in the README. Also, how are the ids for the tokens generated? Can they be anything as long as they're unique?

**Comment by gaotianyu1350** [comment]
``other information`` is optional. The token IDs should be consistent with your word embedding (word vector) data file.

**Comment by danem** [comment]
Sorry, I'm not following. The word to vec data doesn't include any ID information. It's simply a mapping between a word and a set of weights. By ID, I'm referring to the ID field of the head and tail objects.

Thanks for the help.
