### ISSUE TITLE
Need speed optimization for GPU

### ISSUE THREAD

**Issue by billy-inn** [thunlp/OpenNRE#8]
I find that the code seems to be not that friendly to GPU. If a GPU is used, tensorflow will do all the stuff on GPU automatically. But there is a for-loop, which will hurt the speed significantly. In addition, it's better to do the embedding stuff on CPU either, I think. 

I rewrite the code for my own task. The speed using GPU is much slower than CPU. Do you plan to optimize the code for GPU?  By the way, how long do you train the model and use which device?

**Comment by Tsingularity** [comment]
Under the device of GeForce GTX TITAN X, the training process usually takes nearly an hour.

Thank you for your attention for TensorFlow-NRE, and I think your suggestions are really useful. We will implement the GPU optimization in the future work.

**Comment by billy-inn** [comment]
I find where the problem is. In my task, most entity pairs just have a few corresponding sentences (1 or 2). As a result, that for-loop will make my code extremely slow for GPU. Now, I do some over-sampling to pad the training data so that each entity pair has the same amount of sentences. And then, I can vectorize that for-loop. It speeds up my code significantly. 

However, for your dataset, it seems that each entity pair has quite a bit sentences, am I right? And I think that's why it's not so slow for your task.

Do you accept a pull request? Maybe I can vectorize that for-loop and bring some speed improvements. Or you can implement this idea yourselves, it's quite intuitive I think.

**Comment by Tsingularity** [comment]
Yes, in the NYT dataset, a lot of entity pairs have a large number of sentences. And in the initial.py you can see that I use the getsmall() function to split them to avoid out of memory during training, which happens a lot during training if not splitting them. You can also see in the training codes that I check the total number of sentences before feeding them into the feed_dict.

As for the for-loop, because the number of the sentences the entity pairs contain is uncertain, it's really a tough thing for me to do the feed_dict. So I use the for-loop inside the training/testing process which is obviously not the best choice, but I cannot come up with something better than that. If you have a better way, please feel free to inform me or directly make the pull request. In fact, TensorFlow Fold maybe is helpful to the problem.

I think you can do the pull request directly without informing me. We will check the difference and merge them if it actually makes sense.

Thank you for your support and suggestions for TensorFlow-NRE!

**Comment by cloudfengchao** [comment]
In NER taskes, is there any specific advantage of 1) grouping training sentences by entity pair and treating the groups as batches as opposed to 2) flattening all the sentences and using evenly sliced batches?

**Comment by Tsingularity** [comment]
@cloudfengchao 

I think maybe you should read the reference papers listed in ReadMe.md firstly. The reason to group sentences by entity pairs is the sentence-level attention. Different sentences for the same entity pairs contain different amount of information for the relation. And we want to pay attention to the sentences contain more information. If you flatten all the sentences and use evenly sliced batches, each sentence has the average level of attention.

You can see more details in the paper [Lin et al., 2016] Yankai Lin, Shiqi Shen, Zhiyuan Liu, Huanbo Luan, and Maosong Sun. Neural Relation Extraction with Selective Attention over Instances. In Proceedings of ACL.
