### ISSUE TITLE
num_classes = 53 or 58?

### ISSUE THREAD

**Issue by peaceplusone** [thunlp/OpenNRE#9]
hello!
running test.py on my own computer, i got the error below:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [58] rhs shape= [53]
 
Seems like you just set the num_classes = 53, but there are 58 kinds of relationship. ??? 
And when i used the model trained by myself and changed 53 into 58, i can run test.py successfully. 
would u please tell me why "num_classes = 53"?

**Comment by Tsingularity** [comment]
I am really sorry that I uploaded the wrong relation list file during last commit. And now the bug has been fixed.

Thank you for your issues!

**Comment by peaceplusone** [comment]
thanks for your replying!!
and another question: how many epoches needed to converge to the optimization？

**Comment by Tsingularity** [comment]
Sorry for the late response.

About 3~5 epoch, due to the large amount of parameters, it's quite easy for the network to be overfitting. You can split a validation dataset to help evaluate the model during training.

**Comment by peaceplusone** [comment]
Thanks again!!
And i'm still wondering why gru_size =230 ? It's best parameter you've trained? 
If i‘m trying doing some relation extraction work with the Chinese training data, how could i set the gru_size to make my model work well?

**Comment by Tsingularity** [comment]
In the reference paper, it said that 230 is the best size for hidden units/feature vector.

The other reason I choose 230 is that I want to keep the same parameter size with baseline in order to highlight the increase of performance comes from method rather than the increase of parameter size.

I think if you apply to different tasks/projects, you can adjust the hyper parameters (such as learning rate, sentence length, word embedding size, position embedding size, gru or lstm, hidden units size, activation function .etc. ) and observe the performance on validation set. Then you can get the best hyper parameter set fitted for your own task.

**Comment by 1969931493** [comment]
hello!
If you do some relation extraction work with the Chinese training data,Where do the Chinese data come from?Because I was doing the same thing, but I didn't find the right data.

**Comment by tangm00** [comment]
Hello!
I am confused about num_classes：the number of classes is 56 in train.txt and 32 in test.txt, but totally is 58. Why did you set num_classes=53?

**Comment by THUCSTHanxu13** [comment]
There are some relations just in the test set, the previous works often delete these relations from the dataset.
